kind: Deployment
apiVersion: apps/v1
metadata:
  name: fastapi
  labels:
    k8s-app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fastapi
  template:
    metadata:
      labels:
        k8s-app: fastapi
    spec:
      containers:
      - name: fastapi
        image: 'pkvcr.azurecr.io/blkhost/fastapi'
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 250m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
      imagePullSecrets:
      - name: pkvcrsec