FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["FastApi/FastApi.csproj", "FastApi/"]
RUN dotnet restore "FastApi/FastApi.csproj"
COPY . .
WORKDIR "/src/FastApi"
RUN dotnet build "FastApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "FastApi.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "FastApi.dll"]